export const MOVE_SNAKE_RIGHT = 'MOVE_SNAKE_RIGHT';
export const MOVE_SNAKE_LEFT = 'MOVE_SNAKE_LEFT';
export const MOVE_SNAKE_UP = 'MOVE_SNAKE_UP';
export const MOVE_SNAKE_DOWN = 'MOVE_SNAKE_DOWN';
export const STOP_TIMER = 'STOP_TIMER';